INSTALLED_APPS = [
    'django.contrib.auth',
    'django_celery_beat',
    'api',
    'Catalog',
    'Users',
    'Basket',
    'Emails',
    'Statistic',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'adrf',
]
