import os

ROBOKASSA_TEST = os.getenv('ROBOKASSA_TEST')
ROBOKASSA_LOGIN = os.getenv('ROBOKASSA_LOGIN')
ROBOKASSA_PASSWORD_1 = os.getenv('ROBOKASSA_PASSWORD_1')
ROBOKASSA_PASSWORD_2 = os.getenv('ROBOKASSA_PASSWORD_2')
